### ISSUE TITLE
Home page/User can view most popular video games

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/good-games#1]
## Feature
User can see most popular video games/sort by platform

## 📐 Plan
Create a basic home page that shows the most popular video games

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/71413368/106529679-c4d80080-649f-11eb-939b-d5330de58711.png)
![image](https://user-images.githubusercontent.com/71413368/106544817-0a56f680-64bd-11eb-857c-b567269e14f4.png)

 
## ✅ Task List

- [x] Pick fonts to use for the project from Google Fonts
- [x] Import Bootstrap and Font Awesome
- [x] Create a basic nav bar with a logo, search input, and a hamburger menu
- [x] Adjust CSS
- [x] Start building out the home page by adding heading and drop down sort menu
- [x] Adjust CSS
- [x] Make a fetch request to RAWG API, so we can access requested games
- [x] Append photos and game details from the request to our home page
- [x] Add sort platform functionality
- [x] Add platforms to game detail card
- [x] Check functionality
- [x] Fix all styling
- [x] Check Functionality
