### ISSUE TITLE
User can click on hamburger menu and view different pages

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/good-games#2]
## Feature
User can click on hamburger menu to navigate around website

## 📐 Plan
Create a menu component with links to different pages of the site

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/71413368/106529791-f18c1800-649f-11eb-9c36-909c3d3cc804.png)

## ✅ Task List
- [x] Update the navbar component to change the menu icon to an a tag, and set the href to "#menu"
- [x] Create a lib directory/parse-route.js file and define a function that creates a URL path
- [x] Import the parseRoute function inside the app,jsx file and update state with window.location.hash
- [x] Add a window event listener that updates state with the new hash location inside componentDidMount
- [x] Create a menu.jsx 
- [x] Define a renderPage method in app.jsx that checks our route and either returns Home or Menu
- [x] Create a Menu component that renders the provided figma image
- [x] Fix Styling
- [x] Check functionality
