### ISSUE TITLE
User can view newly released games

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/good-games#3]
## Feature
User can see newly released video games/sort by platform

## 📐 Plan
Render the home component, but show newly released games instead

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/71413368/106529537-8b9f9080-649f-11eb-824a-3da43ebc7f18.png)

## ✅ Task List
- [x] Update the gamecard to include links to each platforms store
- [x] Update the renderPage method to return home if any of the paths are equal to new-releases and upcoming-games also passing the route in state to Home
- [x] Pass the route from props to the Games component
- [x] Create a method inside the Games component that makes a fetch request to RAWG API for newly released games
- [x] Update the componentDidMount method to check which path is in route, and call the specific function
- [x] Create a NewReleases component and update the renderpage method to return the newly created component instead of home
- [x] Check Functionality/CSS
