### ISSUE TITLE
User can view upcoming games

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/good-games#4]
## Feature
User can see upcoming games/sort by platform

## 📐 Plan
Render the home component, but show newly upcoming games instead

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/71413368/106529979-4760c000-64a0-11eb-9ead-7d7b98b2872e.png)

## ✅ Task List
- [x] Create a new page for upcomingGames and create a new component
- [x] Update the renderPage method to return UpcomingGames
- [x] Make a fetch request for upcoming games to RAWG API
- [x] Update the componentDidMount and componentDidUpdate to check for a path of "upcoming-games"
- [x] Check functionality
