### ISSUE TITLE
User can go to game page, and see specific details about that game

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/good-games#5]
## Feature
User can view a page with details/reviews about a game

## 📐 Plan
Create a webpage that shows details/reviews about a game

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/71413368/106530822-e4702880-64a1-11eb-8adf-ebbb76035977.png)

## ✅ Task List
- [x] Create a gameDetails page inside the pages folder
- [x] Build a basic render to appear on the screen and update the renderPage method when the path equals "game-details"
- [x] Grab the ID of the game that was clicked on, and pass it to the GameDetails component 
- [x] Make a fetch request to grab details for that game
- [x] Build out the intial page by including some game details at the top, and then images/youtube video
- [x] Bug Fix
- [x] Add a textarea underneath the description so the user can write a review
- [x] Create an endpoint so that a review can get inserted into our database
- [x] Make a fetch request to our database to send the user review
- [x] Make a fetch request to grab reviews from the database
- [x] Add buttons so a user can add a game to their list
- [x] Change styling for user reviews
